---
# tasks file for ansible-ganglia

- name: Create nagios group
  group: >
    name={{ nagios_group }}
    state=present

- name: Create nagios user
  user: >
    name={{ nagios_user }}
    groups={{ nagios_group }}
    append=yes

# Configure the monitoring host.
- include: monitor-redhat.yml
  when: "ansible_os_family == 'RedHat' and inventory_hostname in groups['nagios-monitor']"

- include: monitor-debain.yml
  when: "ansible_os_family == 'Debain' and inventory_hostname == 'nagios-1'" 


# Configure the monitored hosts.
- include: monitored-host-redhat.yml
  when: "ansible_os_family == 'RedHat'"

- include: monitored-host-debain.yml
  when: "ansible_os_family == 'Debain'"
