---
# handlers file for ansible-nagios

- name: restart-apache
  service:
    name: httpd
    state: restarted

- name: restart-nagios
  service:
    name: nagios
    state: restarted

- name: restart-xinetd
  service: 
    name: xinetd
    state: restarted
